### ISSUE TITLE
Facing issue "cannot find name 'MouseWheelEvent'." in Angular 13

### ISSUE THREAD

**Issue by MunkoS** [gabrielbusarello/material2-carousel#29]

**Comment by YukeshM** [comment]
add the following code **interface MouseWheelEvent extends WheelEvent {}** at the end of the file 
carousel.component.d.ts

**Comment by MunkoS** [comment]
bad practice to edit library code

**Comment by Chainsaw-does-brr** [comment]
Had the same issue. Apparently, in one of the newer versions of typescript, a MouseWheelEvent was removed.

As per some dudes advice on the interwebs - add `extensions.d.ts` to your source code with the following:
```
interface MouseWheelEvent extends WheelEvent {}
```

This can help as a temporary solution until #30 is merged.

**Comment by gabrielbusarello** [comment]
Mercedes. Thank you, guys.

**Comment by Chainsaw-does-brr** [comment]
@gabrielbusarello , thanks. Will you be able to publish new version to registry? I noticed last version is 0.7.1, even though you have 0.7.2 listed in repo.

**Comment by joergbaier** [comment]
@gabrielbusarello ^ we would also like a new npm version published (that builds on angular 13)
